---
# Purge

- name: purge ceph mon cluster

  vars:
    mon_group_name:       mons

  hosts: "{{ mon_group_name|default('mons') }}"

  gather_facts: true

  become: true

  tasks:

  - name: stop ceph mons with systemd
    service:
      name: "ceph-{{ item }}@{{ ansible_facts['hostname'] }}"
      state: stopped
      enabled: no
    failed_when: false
    with_items:
      - mon
      - mgr


  - name: remove monitor store and bootstrap keys
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/ceph/mon
      - /var/lib/ceph/bootstrap-mds
      - /var/lib/ceph/bootstrap-osd
      - /var/lib/ceph/bootstrap-rgw
      - /var/lib/ceph/bootstrap-rbd
      - /var/lib/ceph/bootstrap-mgr
      - /var/lib/ceph/tmp

- name: purge ceph-crash daemons
  hosts:
    - "{{ mon_group_name | default('mons') }}"
    - "{{ osd_group_name | default('osds') }}"
    - "{{ mds_group_name | default('mdss') }}"
    - "{{ rgw_group_name | default('rgws') }}"
    - "{{ rbdmirror_group_name | default('rbdmirrors') }}"
    - "{{ mgr_group_name | default('mgrs') }}"
  gather_facts: false
  become: true
  tasks:
    - name: stop ceph-crash service
      service:
        name: ceph-crash.service
        state: stopped
        enabled: no
      failed_when: false

    - name: remove /var/lib/ceph/crash
      file:
        path: /var/lib/ceph/crash
        state: absent