---
# Standard update and reboot if needed

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

#TODO maybe do in apt?
- name: Check if there are available updates
  command: /usr/lib/update-notifier/apt-check --package-names
  register: pkg_list

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

#workaround in the when != ""
- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
  when: pkg_list.stderr | length > 0

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Check if a reboot is required
  stat: path=/var/run/reboot-required get_md5=no
  register: reboot_flag

- name: Reboot the server if needed
  reboot:
    reboot_timeout: 300
  when: reboot_flag.stat.exists

- debug:
    msg: "Server is back up and running"