---
# The hosts need to sync to NTP

- block:
    - name: ntp conf server
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
    
    - name: stop ntp
      service:
        name: ntp
        state: stopped

    - name: sync time once
      shell: ntpd -q -g -x -n
      args:
        executable: /bin/bash
    
    - name: start ntp
      service:
        name: ntp
        state: started
        enabled: True
  when: inventory_hostname == "node1"

- name: get ntp server facts
  setup:
  delegate_to: node1
  delegate_facts: True

- block:
    - name: remove original ntp servers
      lineinfile: dest=/etc/ntp.conf state=absent regexp='(^|\n)server\s.*'
    
    - name: push ntp server to client
      lineinfile: dest=/etc/ntp.conf line="server {{ hostvars[node1]['ansible_default_ipv4']['address'] }} iburst"
      args:
        insertafter: BOF
      delegate_facts: True

    - name: stop ntp
      service:
        name: ntp
        state: stopped

    - name: sync time once
      shell: ntpd -q -g -x -n
      args:
        executable: /bin/bash
  when: not inventory_hostname == "node1"

- name: start ntp
  service:
    name: ntp
    state: started
    enabled: True