---
#Making appropriate pools for the OSDs
# TODO Changed from 128
- name: create pool
  shell: "ceph osd pool create {{ item }} 64 64"
  args:
    executable: /bin/bash
  with_items: "{{ ceph_pools }}"

- name: enable rbd on pools
  shell: ceph osd pool application enable {{ item }} rbd
  args:
    executable: /bin/bash
  with_items: "{{ ceph_pools }}"
