---
# SSH Keypairs

- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} {{ ansible_hostname }}"
    # TODO CLEAN

- block:
    # - name: check root ssh-keypair
    #   stat: path=/root/.ssh/id_ecdsa
    #   register: mon_one_check_ssh_keypair
    
    - name: create new ssh-keypair for root
      # when: mon_one_check_ssh_keypair.stat.exists == False
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 521
        ssh_key_file: .ssh/id_ecdsa
        ssh_key_type: ecdsa
  when: inventory_hostname == "mon_one"

- block:
    - name: get pubkey
      shell: cat /root/.ssh/id_ecdsa.pub
      register: mon_one_ssh_pubkey
      delegate_to: "{{ mon_one }}"

    - set_fact:
        ceph_sync_pub_key: "{{ mon_one_ssh_pubkey.stdout }}"

    - name: check ssh folder for root
      file: dest=/root/.ssh
      args:
        owner: root
        mode: 0700
        state: directory
        recurse: yes

    - name: push pubkey to host
      authorized_key:
        user: root
        state: present
        key: "{{ ceph_sync_pub_key }}"
        manage_dir: True
  when: not inventory_hostname == "mon_one"