---
#Ceph configuration

- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - debug: var=inventory_hostname

# NTP role
- hosts: all
  become: yes
  gather_facts: yes
  roles: 
    - ntp

# First mon
- hosts: node1
  become: yes
  gather_facts: no
  roles:
    - ceph-conf
    - keys
    - mon
    - mgr
  tags: 
    - run_mon
    
# Synchronization of the other mons
- hosts: node2,node3
  become: yes
  gather_facts: no
  roles: 
    - ceph-conf-sync
  tags:
    - synchro
    
# Making of the other mons
- hosts: node2,node3
  become: yes
  gather_facts: no
  roles: 
    - quorum
  tags:
    - other_mons
    
# # Making of the osds
# - block:
#     - role: block-devices
#     - block:
#         - role: osd
#           when: ceph_osd_format == "filestore" or ceph_osd_format == "bluestore"
#           with_items: "{{ free_disks }}"
#           loop_control:
#             loop_var: free_osd
#       when: free_disks is defined
#   when: inventory_hostname in groups['osds']

# # Pool creation
# - role: pool
#   when: ansible_hostname == node1

# # RDB creation
# - block:
#     - role: rbd
#   when: inventory_hostname in groups['clients']
